
FROM eclipse-temurin:17-jre
WORKDIR /app

# Copy the pre-compiled files 
COPY target/classes /app/classes
COPY target/dependency /app/dependency


EXPOSE 8080

# Pre-create the volume folders to prevent Kubernetes "Permission Denied" errors
RUN mkdir -p /app/bitcask_data /app/parquet_archives

# Execute the Central Station
ENTRYPOINT ["java", "-cp", "/app/classes:/app/dependency/*", "com.weather.centralstation.CentralStation"]