FROM eclipse-temurin:17-jre
WORKDIR /app

# Copy the pre-compiled files directly from your Mac's target folder
COPY target/classes /app/classes
COPY target/dependency /app/dependency

# Execute the Weather Station
ENTRYPOINT ["java", "-cp", "/app/classes:/app/dependency/*", "com.weather.stations.WeatherStation"]